#run all scripts

# Run all
rm(list = ls())
print('CLEANING STUDY 1A')
source('scripts/clean_norming_data_study1a.R')
rm(list = ls())
print('CLEANING STUDY 1B')
source('scripts/clean_norming_data_study1b.R')
rm(list = ls())
print('CLEANING STUDY 2')
source('scripts/clean_study2.R')
rm(list = ls())
print('MAKING MC TABLE VALENCE')
source('scripts/make_MC_table_study1a.R')
rm(list = ls())
print('MAKING MC TABLE SOURCE')
source('scripts/make_mcTableSource.R')
rm(list=ls())
print('COMPUTING CRONBACHS ALPHA')
source('scripts/compute_alpha.R')
rm(list=ls())
print('TEST H1')
source('scripts/make_cravingTable_1b.R')
rm(list=ls())
print('MAKING CRAVING TABLE')
source('scripts/make_cravingTable.R')
rm(list = ls())
print('MAKING BINGE TABLE')
source('scripts/make_bingeTable.R')
rm(list = ls())
print('MAKING EMO TABLE')
source('scripts/make_emoTable.R')
rm(list = ls())
print('MAKING FAMILIARITY TABLE')
source('scripts/make_familiarityTable.R')
